import React, { useEffect, useMemo, useState } from "react";

// BUILD VERSION: donor-sign-portal-no-appbutton-v2
// This version intentionally uses only plain HTML <button> elements.

// SUPABASE SETTINGS
const SUPABASE_URL = "https://ldfmgmttwtsanzausdcl.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_4EijCGn3OePLahvT9CZHbQ_PMkdpoQX";
const STORAGE_BUCKET = "calendar-files";
const TABLE_NAME = "calendar_uploads";
const DATE_COLUMN = "date";

// JEWISH CALENDAR SETTINGS
// Keep false for New York / Diaspora. Set true for Israel.
const ISRAEL_CALENDAR = false;
const SHOW_MINOR_JEWISH_DATES = true;

const monthNames = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

const weekDays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function getMonthDays(year, month) {
  const firstDay = new Date(year, month, 1).getDay();
  const totalDays = new Date(year, month + 1, 0).getDate();
  const list = [];

  for (let i = 0; i < firstDay; i += 1) list.push(null);
  for (let day = 1; day <= totalDays; day += 1) list.push(day);

  return list;
}

function getJewishDate(date) {
  try {
    return new Intl.DateTimeFormat("en-u-ca-hebrew", {
      day: "numeric",
      month: "short"
    }).format(date);
  } catch {
    return "";
  }
}

function getTodayKey() {
  return formatDate(new Date());
}

function getLocalUploads() {
  try {
    if (typeof localStorage === "undefined") return {};
    return JSON.parse(localStorage.getItem("calendarUploads") || "{}");
  } catch {
    return {};
  }
}

function saveLocalUploads(data) {
  try {
    if (typeof localStorage !== "undefined") {
      localStorage.setItem("calendarUploads", JSON.stringify(data));
    }
  } catch {
    // Local storage can be blocked by the browser.
  }
}

function cleanJewishTitle(item) {
  const title = item.title || "";

  if (item.category === "parashat") {
    return title.startsWith("Parashat ") ? title.replace("Parashat ", "Parsha: ") : `Parsha: ${title}`;
  }

  return title;
}

function shouldShowJewishEvent(item) {
  if (!item || !item.date || !item.title) return false;

  const category = item.category || "";
  const subcat = item.subcat || "";

  if (category === "parashat") return true;
  if (category === "holiday") return true;
  if (category === "roshchodesh") return true;
  if (category === "omer") return false;
  if (category === "dafyomi") return false;
  if (category === "candles") return false;
  if (category === "havdalah") return false;
  if (!SHOW_MINOR_JEWISH_DATES && subcat === "minor") return false;

  return false;
}

function mapHebcalItems(items) {
  const mapped = {};

  (items || []).forEach((item) => {
    if (!shouldShowJewishEvent(item)) return;

    const dateKey = String(item.date || "").slice(0, 10);
    if (!dateKey) return;

    const event = {
      title: cleanJewishTitle(item),
      category: item.category || "holiday",
      yomTov: Boolean(item.yomtov)
    };

    if (!mapped[dateKey]) mapped[dateKey] = [];
    mapped[dateKey].push(event);
  });

  return mapped;
}

async function fetchJewishEvents(startDate, endDate) {
  const params = new URLSearchParams({
    cfg: "json",
    v: "1",
    start: startDate,
    end: endDate,
    maj: "on",
    min: "on",
    mod: "on",
    nx: "on",
    mf: "on",
    ss: "on",
    s: "on",
    c: "off",
    geo: "none",
    i: ISRAEL_CALENDAR ? "on" : "off",
    lg: "s"
  });

  const response = await fetch(`https://www.hebcal.com/hebcal?${params.toString()}`);
  if (!response.ok) throw new Error("Could not load Jewish calendar events");

  const data = await response.json();
  return mapHebcalItems(data.items || []);
}

function canUseSupabase() {
  return Boolean(SUPABASE_URL && SUPABASE_ANON_KEY);
}

function supabaseHeaders(extra = {}) {
  return {
    apikey: SUPABASE_ANON_KEY,
    Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
    ...extra
  };
}

async function readErrorText(response) {
  try {
    const text = await response.text();
    return text || `${response.status} ${response.statusText}`;
  } catch {
    return `${response.status} ${response.statusText}`;
  }
}

function getSetupSql() {
  return `create table if not exists calendar_uploads (
  id bigint generated by default as identity primary key,
  date date not null unique,
  file_name text not null,
  file_url text not null,
  file_type text,
  created_at timestamptz default now()
);`;
}

function makeSchemaError(details) {
  return new Error(`Supabase table setup needed. The table must have columns: date, file_name, file_url, file_type. Details: ${details}`);
}

async function supabaseSelectUploads(startDate, endDate) {
  const url = `${SUPABASE_URL}/rest/v1/${TABLE_NAME}?select=${DATE_COLUMN},file_name,file_url,file_type&${DATE_COLUMN}=gte.${startDate}&${DATE_COLUMN}=lte.${endDate}`;
  const response = await fetch(url, {
    headers: supabaseHeaders({ Accept: "application/json" })
  });

  if (!response.ok) {
    const details = await readErrorText(response);
    if (details.includes("42703") || details.includes("does not exist")) {
      throw makeSchemaError(details);
    }
    throw new Error(`Could not load uploads: ${details}`);
  }

  return response.json();
}

async function supabaseSelectToday(today) {
  const url = `${SUPABASE_URL}/rest/v1/${TABLE_NAME}?select=${DATE_COLUMN},file_name,file_url,file_type&${DATE_COLUMN}=eq.${today}&limit=1`;
  const response = await fetch(url, {
    headers: supabaseHeaders({ Accept: "application/json" })
  });

  if (!response.ok) {
    const details = await readErrorText(response);
    if (details.includes("42703") || details.includes("does not exist")) {
      throw makeSchemaError(details);
    }
    throw new Error(`Could not load today upload: ${details}`);
  }

  const rows = await response.json();
  return rows[0] || null;
}

async function supabaseUploadFile(dateKey, file) {
  const cleanFileName = file.name.replace(/[^a-zA-Z0-9._-]/g, "-");
  const filePath = `${dateKey}/${Date.now()}-${cleanFileName}`;
  const uploadUrl = `${SUPABASE_URL}/storage/v1/object/${STORAGE_BUCKET}/${filePath}`;

  const uploadResponse = await fetch(uploadUrl, {
    method: "POST",
    headers: supabaseHeaders({
      "Content-Type": file.type || "application/octet-stream",
      "x-upsert": "true"
    }),
    body: file
  });

  if (!uploadResponse.ok) {
    const details = await readErrorText(uploadResponse);
    throw new Error(`Could not upload file: ${details}`);
  }

  const publicUrl = `${SUPABASE_URL}/storage/v1/object/public/${STORAGE_BUCKET}/${filePath}`;

  const saveResponse = await fetch(`${SUPABASE_URL}/rest/v1/${TABLE_NAME}`, {
    method: "POST",
    headers: supabaseHeaders({
      "Content-Type": "application/json",
      Prefer: "resolution=merge-duplicates"
    }),
    body: JSON.stringify({
      [DATE_COLUMN]: dateKey,
      file_name: file.name,
      file_url: publicUrl,
      file_type: file.type || "application/octet-stream"
    })
  });

  if (!saveResponse.ok) {
    const details = await readErrorText(saveResponse);
    throw new Error(`Could not save upload record: ${details}`);
  }

  return {
    name: file.name,
    url: publicUrl,
    type: file.type || "application/octet-stream"
  };
}

async function supabaseDeleteUpload(dateKey) {
  const deleteUrl = `${SUPABASE_URL}/rest/v1/${TABLE_NAME}?${DATE_COLUMN}=eq.${dateKey}`;
  const response = await fetch(deleteUrl, {
    method: "DELETE",
    headers: supabaseHeaders({ Prefer: "return=minimal" })
  });

  if (!response.ok) {
    const details = await readErrorText(response);
    throw new Error(`Could not remove upload: ${details}`);
  }
}

function renderPreview(file) {
  if (!file) return null;

  if (file.type && file.type.startsWith("image/")) {
    return <img src={file.url} alt={file.name} className="w-full max-h-[500px] object-contain rounded-xl bg-gray-100" />;
  }

  if (file.type && file.type.startsWith("video/")) {
    return <video src={file.url} className="w-full max-h-[500px] rounded-xl bg-black" controls />;
  }

  if (file.type === "application/pdf") {
    return <iframe title={file.name} src={file.url} className="w-full h-[500px] rounded-xl border bg-white" />;
  }

  return (
    <div className="rounded-xl bg-gray-100 p-6 text-center text-gray-700">
      Preview is not available for this file type.
    </div>
  );
}

function runBasicTests() {
  console.assert(formatDate(new Date(2026, 0, 5)) === "2026-01-05", "formatDate should use YYYY-MM-DD");
  console.assert(getMonthDays(2026, 0).filter(Boolean).length === 31, "January 2026 should have 31 days");
  console.assert(getMonthDays(2026, 1).filter(Boolean).length === 28, "February 2026 should have 28 days");
  console.assert(getMonthDays(2024, 1).filter(Boolean).length === 29, "February 2024 should have 29 days");
  console.assert(getMonthDays(2026, 4)[0] === null || getMonthDays(2026, 4)[0] === 1, "Month days should contain blanks or day 1 first");
  console.assert(typeof getJewishDate(new Date(2026, 0, 1)) === "string", "Jewish date should return a string");
  console.assert("rgb(32, 73, 114)".startsWith("rgb"), "Brand blue should be valid");
  console.assert("rgb(245, 132, 65)".startsWith("rgb"), "Brand orange should be valid");
  console.assert("rgb(251, 176, 60)".startsWith("rgb"), "Brand gold should be valid");
  console.assert("B Visible Donor Sign Portal".includes("Visible"), "Header text should include Visible");
  console.assert(typeof renderPreview === "function", "Preview renderer should exist");
  console.assert(typeof readErrorText === "function", "Supabase error reader should exist");
  console.assert(DATE_COLUMN === "date", "Date column should be date");
  console.assert(getSetupSql().includes("file_url"), "Setup SQL should include file_url");
  console.assert(!"AppButton".includes("PlainButtonOnly"), "This build does not use AppButton");
  console.assert(canUseSupabase() === true, "Supabase config should be present");

  const sampleHebcal = mapHebcalItems([
    { date: "2026-04-04", title: "Pesach I", category: "holiday", yomtov: true },
    { date: "2026-04-04", title: "Parashat Tzav", category: "parashat" },
    { date: "2026-04-05", title: "1st day of the Omer", category: "omer" }
  ]);

  console.assert(sampleHebcal["2026-04-04"].length === 2, "Holiday and parsha should be mapped");
  console.assert(sampleHebcal["2026-04-04"][1].title === "Parsha: Tzav", "Parsha title should be cleaned");
  console.assert(!sampleHebcal["2026-04-05"], "Omer-only days should be hidden");
}

runBasicTests();

export default function SimpleCalendarUpload() {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState(null);
  const [uploads, setUploads] = useState({});
  const [screenFile, setScreenFile] = useState(null);
  const [isUploading, setIsUploading] = useState(false);
  const [previewFile, setPreviewFile] = useState(null);
  const [jewishEvents, setJewishEvents] = useState({});
  const [jewishEventsStatus, setJewishEventsStatus] = useState("loading");
  const [message, setMessage] = useState("");

  const searchParams = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : new URLSearchParams();
  const isScreenMode = searchParams.get("screen") === "player";

  const year = currentDate.getFullYear();
  const month = currentDate.getMonth();
  const days = useMemo(() => getMonthDays(year, month), [year, month]);

  async function loadUploads() {
    if (!canUseSupabase()) {
      setUploads(getLocalUploads());
      return;
    }

    try {
      const lastDayOfMonth = String(new Date(year, month + 1, 0).getDate()).padStart(2, "0");
      const monthNumber = String(month + 1).padStart(2, "0");
      const rows = await supabaseSelectUploads(`${year}-${monthNumber}-01`, `${year}-${monthNumber}-${lastDayOfMonth}`);
      const mapped = {};

      (rows || []).forEach((item) => {
        mapped[item[DATE_COLUMN]] = {
          name: item.file_name,
          url: item.file_url,
          type: item.file_type
        };
      });

      setUploads(mapped);
    } catch (error) {
      setMessage(`${error.message || "Could not load Supabase uploads."} Using local browser storage for now.`);
      setUploads(getLocalUploads());
    }
  }

  async function loadJewishEvents() {
    setJewishEventsStatus("loading");

    try {
      const firstDate = `${year}-${String(month + 1).padStart(2, "0")}-01`;
      const lastDate = `${year}-${String(month + 1).padStart(2, "0")}-${String(new Date(year, month + 1, 0).getDate()).padStart(2, "0")}`;
      const events = await fetchJewishEvents(firstDate, lastDate);
      setJewishEvents(events);
      setJewishEventsStatus("ready");
    } catch (error) {
      console.error(error);
      setJewishEvents({});
      setJewishEventsStatus("offline");
    }
  }

  async function loadTodayForScreen() {
    const today = getTodayKey();

    if (!canUseSupabase()) {
      const localUploads = getLocalUploads();
      setScreenFile(localUploads[today] || null);
      return;
    }

    try {
      const data = await supabaseSelectToday(today);
      setScreenFile(data ? {
        name: data.file_name,
        url: data.file_url,
        type: data.file_type
      } : null);
    } catch (error) {
      console.error(error);
      setScreenFile(null);
    }
  }

  useEffect(() => {
    if (isScreenMode) {
      loadTodayForScreen();
      const interval = setInterval(loadTodayForScreen, 5 * 60 * 1000);
      return () => clearInterval(interval);
    }

    loadUploads();
    loadJewishEvents();
  }, [year, month, isScreenMode]);

  async function handleFileUpload(event) {
    const file = event.target.files && event.target.files[0];
    if (!file || !selectedDate) return;

    setMessage("");
    setIsUploading(true);
    const dateKey = formatDate(selectedDate);

    try {
      if (!canUseSupabase()) {
        const fileUrl = URL.createObjectURL(file);
        const nextUploads = {
          ...uploads,
          [dateKey]: {
            name: file.name,
            url: fileUrl,
            type: file.type
          }
        };

        setUploads(nextUploads);
        setPreviewFile(nextUploads[dateKey]);
        saveLocalUploads(nextUploads);
      } else {
        const uploadedFile = await supabaseUploadFile(dateKey, file);
        setPreviewFile(uploadedFile);
        await loadUploads();
      }
    } catch (error) {
      setMessage(`${error.message || "Upload failed."} Check that the Supabase table, storage bucket, and policies are created.`);
    } finally {
      setIsUploading(false);
      event.target.value = "";
    }
  }

  async function removeSelectedUpload() {
    if (!selectedDate) return;

    setMessage("");
    const dateKey = formatDate(selectedDate);

    try {
      if (!canUseSupabase()) {
        const nextUploads = { ...uploads };
        delete nextUploads[dateKey];
        setUploads(nextUploads);
        saveLocalUploads(nextUploads);
      } else {
        await supabaseDeleteUpload(dateKey);
        await loadUploads();
      }

      setPreviewFile(null);
    } catch (error) {
      setMessage(`${error.message || "Remove failed."} Check Supabase delete policy for the calendar_uploads table.`);
    }
  }

  function goPreviousMonth() {
    setCurrentDate(new Date(year, month - 1, 1));
  }

  function goNextMonth() {
    setCurrentDate(new Date(year, month + 1, 1));
  }

  const selectedDateKey = selectedDate ? formatDate(selectedDate) : null;
  const selectedJewishEvents = selectedDateKey ? jewishEvents[selectedDateKey] || [] : [];
  const selectedUpload = selectedDateKey ? uploads[selectedDateKey] : null;

  if (isScreenMode) {
    return (
      <div className="w-screen h-screen bg-black text-white flex items-center justify-center overflow-hidden">
        {!screenFile && (
          <div className="text-center p-8">
            <div className="text-6xl mb-6">▣</div>
            <h1 className="text-4xl font-bold mb-3">No file scheduled for today</h1>
            <p className="text-xl opacity-70">Today: {getTodayKey()} • {getJewishDate(new Date())}</p>
          </div>
        )}

        {screenFile && renderPreview(screenFile)}
      </div>
    );
  }

  return (
    <div className="min-h-screen p-4 md:p-8" style={{ background: "linear-gradient(135deg, #0f2233 0%, #0b1a28 60%, #08131d 100%)" }}>
      <div className="max-w-6xl mx-auto">
        <div className="mb-6 text-center">
          <h1 className="text-3xl md:text-4xl font-bold text-white">
            B Visible Donor Sign Portal
          </h1>
          <div className="mt-4 flex items-center justify-center gap-3 text-white">
            <span className="text-3xl">▣</span>
            <span className="text-2xl md:text-3xl font-bold">Calendar Upload</span>
          </div>
          <p className="text-white/90 mt-2">Click a date, upload a file, and it will show on that day.</p>
          <p className="text-white/50 text-xs mt-1">Build: no AppButton v2</p>
        </div>

        {message && (
          <div className="mb-4 rounded-2xl border border-orange-200 bg-orange-50 p-4 text-sm text-orange-900">
            {message}
          </div>
        )}

        <div className="rounded-2xl shadow-lg bg-white border border-gray-200">
          <div className="p-4 md:p-6">
            <div className="flex items-center justify-between mb-6">
              <button
                type="button"
                onClick={goPreviousMonth}
                aria-label="Previous month"
                className="inline-flex items-center justify-center rounded-xl border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-800 shadow-sm transition hover:bg-gray-50"
              >
                ‹
              </button>

              <div className="text-center">
                <h2 className="text-2xl font-bold" style={{ color: "rgb(32, 73, 114)" }}>
                  {monthNames[month]} {year}
                </h2>
                <p className="text-sm font-medium" style={{ color: "rgb(245, 132, 65)" }}>
                  Jewish dates, holidays, and parsha shown inside each day
                </p>
                {jewishEventsStatus === "offline" && (
                  <p className="text-xs text-orange-700 mt-1">
                    Jewish holidays could not load. Check internet connection.
                  </p>
                )}
              </div>

              <button
                type="button"
                onClick={goNextMonth}
                aria-label="Next month"
                className="inline-flex items-center justify-center rounded-xl border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-800 shadow-sm transition hover:bg-gray-50"
              >
                ›
              </button>
            </div>

            <div className="grid grid-cols-7 gap-2 mb-2 text-center font-semibold text-gray-600">
              {weekDays.map((day) => (
                <div key={day} className="p-2">{day}</div>
              ))}
            </div>

            <div className="grid grid-cols-7 gap-2">
              {days.map((day, index) => {
                if (!day) return <div key={`blank-${index}`} className="min-h-32" />;

                const date = new Date(year, month, day);
                const dateKey = formatDate(date);
                const upload = uploads[dateKey];
                const events = jewishEvents[dateKey] || [];
                const isSelected = selectedDate && formatDate(selectedDate) === dateKey;
                const isToday = dateKey === getTodayKey();

                return (
                  <button
                    key={dateKey}
                    type="button"
                    onClick={() => {
                      setSelectedDate(date);
                      setPreviewFile(upload || null);
                    }}
                    className={`min-h-32 rounded-2xl border p-3 text-left transition bg-white hover:bg-blue-50 hover:border-blue-300 ${
                      isSelected ? "border-blue-600 ring-2 ring-blue-200" : "border-gray-200"
                    } ${isToday ? "bg-orange-50 border-orange-300" : ""}`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div>
                        <div className="font-bold text-gray-900">{day}</div>
                        <div className="text-[11px] font-medium mt-1" style={{ color: "rgb(32, 73, 114)" }}>
                          {getJewishDate(date)}
                        </div>
                      </div>
                      {isToday && <span className="text-[10px] bg-orange-200 text-orange-900 px-2 py-1 rounded-full">Today</span>}
                    </div>

                    {events.length > 0 && (
                      <div className="mt-2 space-y-1">
                        {events.slice(0, 3).map((event, eventIndex) => (
                          <div
                            key={`${dateKey}-${event.title}-${eventIndex}`}
                            className={`text-[10px] rounded-lg px-2 py-1 font-semibold leading-tight ${
                              event.category === "parashat"
                                ? "bg-purple-100 text-purple-800"
                                : event.yomTov
                                  ? "bg-yellow-100 text-yellow-900"
                                  : "bg-blue-100 text-blue-800"
                            }`}
                          >
                            {event.title}
                          </div>
                        ))}
                        {events.length > 3 && (
                          <div className="text-[10px] text-gray-500">+{events.length - 3} more</div>
                        )}
                      </div>
                    )}

                    {upload && (
                      <div className="mt-3 text-xs bg-green-100 text-green-800 rounded-xl p-2 break-words">
                        {upload.name}
                      </div>
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        <div className="rounded-2xl shadow-lg mt-6 bg-white border border-gray-200">
          <div className="p-4 md:p-6">
            <h3 className="text-xl font-bold mb-2">Upload File</h3>

            {!selectedDate && <p className="text-gray-600">Select a date first.</p>}

            {selectedDate && (
              <div className="space-y-4">
                <div className="text-gray-700">
                  Selected date: <strong>{formatDate(selectedDate)}</strong>
                  <span className="text-blue-700 font-medium"> • {getJewishDate(selectedDate)}</span>
                </div>

                {selectedJewishEvents.length > 0 && (
                  <div className="rounded-2xl bg-blue-50 border border-blue-100 p-4">
                    <div className="font-bold text-blue-900 mb-2">Jewish calendar</div>
                    <div className="flex flex-wrap gap-2">
                      {selectedJewishEvents.map((event, index) => (
                        <span
                          key={`${event.title}-${index}`}
                          className={`text-xs rounded-full px-3 py-1 font-semibold ${
                            event.category === "parashat"
                              ? "bg-purple-100 text-purple-800"
                              : event.yomTov
                                ? "bg-yellow-100 text-yellow-900"
                                : "bg-blue-100 text-blue-800"
                          }`}
                        >
                          {event.title}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                <label className="flex items-center justify-center gap-3 border-2 border-dashed rounded-2xl p-8 bg-white hover:bg-orange-50 cursor-pointer" style={{ borderColor: "rgb(245, 132, 65)" }}>
                  <span className="text-2xl">↑</span>
                  <span className="font-semibold">{isUploading ? "Uploading..." : selectedUpload ? "Replace file" : "Choose file"}</span>
                  <input type="file" className="hidden" onChange={handleFileUpload} disabled={isUploading} />
                </label>

                {selectedUpload && (
                  <div className="rounded-2xl border bg-white p-4 shadow-sm" style={{ borderColor: "rgb(251, 176, 60)" }}>
                    <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
                      <div>
                        <div className="font-bold" style={{ color: "rgb(32, 73, 114)" }}>Uploaded file</div>
                        <div className="text-sm text-gray-600 break-words">{selectedUpload.name}</div>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        <button
                          type="button"
                          onClick={() => setPreviewFile(selectedUpload)}
                          className="inline-flex items-center justify-center rounded-xl border border-[#204972] bg-[#204972] px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-[#183957]"
                        >
                          Preview
                        </button>
                        <button
                          type="button"
                          onClick={removeSelectedUpload}
                          className="inline-flex items-center justify-center rounded-xl border border-[#f58441] bg-[#f58441] px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-[#df7437]"
                        >
                          Remove
                        </button>
                      </div>
                    </div>
                  </div>
                )}

                {previewFile && (
                  <div className="rounded-2xl border bg-white p-4 shadow-sm" style={{ borderColor: "rgb(32, 73, 114)" }}>
                    <div className="flex items-center justify-between gap-3 mb-3">
                      <div>
                        <div className="font-bold" style={{ color: "rgb(32, 73, 114)" }}>Preview</div>
                        <div className="text-sm text-gray-600 break-words">{previewFile.name}</div>
                      </div>
                      <button
                        type="button"
                        onClick={() => setPreviewFile(null)}
                        className="inline-flex items-center justify-center rounded-xl border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-800 shadow-sm transition hover:bg-gray-50"
                      >
                        Close
                      </button>
                    </div>

                    {renderPreview(previewFile)}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
